[package]
name = "loggerv"
version = "0.2.0"
authors = ["Eirik Albrigtsen <analsandblaster@gmail.com>"]
repository = "https://github.com/clux/loggerv"
documentation = "http://clux.github.io/loggerv"
license = "MIT"
keywords = ["log", "logger", "stdio", "cli"]
description = """
A simple log implementation that logs to stdout and stderr with colors
"""

[dependencies]
log = "0.3.5"
ansi_term = "0.7.2"

[[example]]
name = "clap"
path = "examples/clap.rs"

[dev-dependencies]
clap = "2.1.2"
