version: 2.1

workflows:
  all_jobs:
    jobs:
      - tests
      - coverage:
          filters:
            branches:
              only:
                - master
jobs:
  tests:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: grep "\[dependencies\]" -A 9000 Cargo.toml > deps_checksum
      - restore_cache:
          keys:
          - cache-{{ checksum "deps_checksum" }}
      - run: cargo build
      - run: cargo test --lib -j8
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target/debug/.fingerprint
            - target/debug/build
            - target/debug/deps
          key: cache-{{ checksum "deps_checksum" }}
  coverage:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            docker run \
              --security-opt seccomp=unconfined \
              -v "${PWD}:/volume" \
              -e /bin/sh xd009642/tarpaulin \
              cargo build && cargo tarpaulin --coveralls=${COVERALLS_REPO_TOKEN}
