[package]
name = "example"
version = "0.1.0"
authors = ["Eirik Albrigtsen <analsandblaster@gmail.com>"]

[[bin]]
name = "app"
path = "clap.rs"


[dependencies]
log = "0.3.5"
clap = "2.1.2"

[dependencies.loggerv]
version = "0.1"
path = ".."
